### ISSUE TITLE
Put more verbs in the glossary

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/safe_arch#51]
For any operation name that isn't already so common it's in the rust core lib (eg: add and sqrt) we should put them into the verb glossary.

And if it gets big enough, we might want to put the verb glossary on its own page.

**Comment by Soveu** [comment]
Ordered vs Unordered comparisons
(answer from [https://stackoverflow.com/questions/8627331/what-does-ordered-unordered-comparison-mean](url))
`An ordered comparison checks if neither operand is NaN. Conversely, an unordered comparison checks if either operand is a NaN.`

**Comment by Soveu** [comment]
Fused operation
For example when calculating normally `a * b + c` (a, b, c are floats), there are two rounding operations: 

- after `a * b` 
- after adding `c` to previous result

Fusing these operations means only one rounding at the end is performed.
This happens because internally CPUs calculate with slightly higher precision

**Comment by Lokathor** [comment]
https://github.com/Lokathor/safe_arch/blob/master/nomoj.txt
