### ISSUE TITLE
Delete underscores from submodule filenames

### ISSUE THREAD

**Issue by Soveu** [Lokathor/safe_arch#63]
They are just annoying to type everytime

**Comment by Soveu** [comment]
Or maybe we should re-organize code a little bit
Now `src/lib.rs` mostly contains code related to x86/x64 arch, I suggest to move it into `src/x86_x64/mod.rs`.
It will make `lib.rs` cleaner and ready for other architectures

**Comment by Lokathor** [comment]
the underscores have to be there or it conflicts with the naming of the type, since module paths and type paths "live in the same namespace" in the eyes of rust.

**Comment by Lokathor** [comment]
As to a total re-organization, I'm not against the general idea, and I agree that once ARM intrinsics are ready to be added we might have to re-think things, but I've really never liked either `mod.rs` or `foo.rs` being next to the `foo/` folder. I'm pretty big on this new inline module based style that I was shown a few months ago, since it lets you avoid both.
